### ISSUE TITLE
Getting started on git

### ISSUE THREAD

**Issue by qafui** [Didionez/4rentgh#2]
Hey, 

Thanks for adding me. I'm currently enrolled in a programming bootcamp and may be able to bring some of the knowledge I'm gaining to your project. 

I notice you're new to github. It will be helpful to spend sometime mastering it's basic concepts using this: https://github.github.io/on-demand/

Best regards,

PS: please respond and let me know what you think about github and my comments. Do close this ticket when you're done.

**Comment by Didionez** [comment]
Hello Qafui,im not really an IT person so i dont understand everything here but i think its a good environment for learning

**Comment by Didionez** [comment]
My sis also told me you would like to help me make my site look a bit more better i would be glad if u share the mistakes u've noticed.The problem i have with the website now customers can only post one pic,i would be very glad if u could help me increase it to a maximum of five pictures.
