### ISSUE TITLE
Source code & Collaboration

### ISSUE THREAD

**Issue by qafui** [Didionez/4rentgh#3]
> Didionez: David the guy who helped me put the file on github says uve been made a collaborator so u should be able to see the source code

There's currently no source code uploaded to github. This is what I mean;
1. Example of source code on github
   <img width="1030" alt="screen shot 2016-09-29 at 03 18 40" src="https://cloud.githubusercontent.com/assets/3660972/18944451/acc932fa-85f3-11e6-87bd-37df6ce1fb8b.png">
2. Source code section on 4rentgh
   <img width="1049" alt="screen shot 2016-09-29 at 03 21 16" src="https://cloud.githubusercontent.com/assets/3660972/18944512/f0f41e90-85f3-11e6-8667-26184f1b4e46.png">

Could you show this to him please?

**Comment by Didionez** [comment]
Would it be okay if i could email you the zipped file.

**Comment by qafui** [comment]
No worries. I found the zip file. Please refer to the issues table for comments.

**Comment by Didionez** [comment]
Okay
