### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by Didionez** [Didionez/4rentgh#5]
Hello David are u on whatsapp if so kindly gve me ur contact so that we have better communication or u might as well gv me ur facebook account name.

**Comment by qafui** [comment]
Hi Theodore, just moved to the U.S. Don't have whatsapp yet and I don't use Facebook anymore. I'm available on twitter as [@qafui](https://twitter.com/qafui). Will let you know when I get a U.S number for whatsapp.

**Comment by Didionez** [comment]
Boss pls for the company account could u make it in a way that the company could be able to post a profile pic (company image) and a description box for what they do.pls sorry being late with this one

**Comment by qafui** [comment]
Let's have a skype chat in 3 hours. Use the email address qafui@outlook.com to find me.

**Comment by Didionez** [comment]
Sorry David my phone was off didnt see it early.very sorry.

**Comment by Didionez** [comment]
We could reschedule if u arent busy
