### ISSUE TITLE
Rewriting the app

### ISSUE THREAD

**Issue by qafui** [Didionez/4rentgh#6]
Hey, if you're interested in really putting out a product I can work on it with you in terms of the technical coding part to get it off the ground and deployed. You'd just have to wait until mid-April when i complete a project im currently working on.

**Comment by Didionez** [comment]
Okay then i would wait.Thank you

**Comment by Didionez** [comment]
Hello David how r u doing ?? ,hope you good ,pls im having having a problem
with how the site looks on various phones and tabs

**Comment by Didionez** [comment]
Hello Mr David hope u good ?? I was writing my exams in April so i was soo
busy i couldnt remind you of your kind gesture to help me concerning the
website.If youre not too busy i hope we could start something.

**Comment by qafui** [comment]
Sure man, what do you need help with?

**Comment by Didionez** [comment]
Goodevening Mr David im humbly asking to please help with these task

1.Email confirmation for registering


2.OAuth to authenticate with social media Allow users to login with
Facebook or twitter or instagram.The product will be posted on the social
media account immediately the product is registered.


3.A payment system where people can pay for a top ad


4.The site should be able to fit the various phone sizes screen.


5. A consistent and responsive Web design with quick navigation cues


6

. A FAQ section with details on how to use website.


Kindly feel free to add what u think fits and suits the site.Thank u.
